language: ruby
dist: trusty
sudo: required
before_install:
  - gem install bundler # the default bundler version on travis is very old and causes 1.9.3 build issues
rvm:
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
  - jruby-9.1.17.0
  - jruby-9.2.0.0
  - rbx-3
